"""add_contract_models

Revision ID: 520bece3496b
Revises: 
Create Date: 2026-06-11 09:55:59.998563
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '520bece3496b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('contract_type_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('ocr_completed_at', sa.DateTime(), nullable=True),
    sa.Column('extraction_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_content_hash'), 'contracts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_table('contract_clauses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('clause_type', sa.String(length=50), nullable=True),
    sa.Column('clause_title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cc_contract_type', 'contract_clauses', ['contract_id', 'clause_type'], unique=False)
    op.create_index(op.f('ix_contract_clauses_contract_id'), 'contract_clauses', ['contract_id'], unique=False)
    op.create_table('contract_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cfile_contract_version', 'contract_files', ['contract_id', 'version'], unique=False)
    op.create_index(op.f('ix_contract_files_contract_id'), 'contract_files', ['contract_id'], unique=False)
    op.create_table('contract_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_tasks_contract_id'), 'contract_tasks', ['contract_id'], unique=False)
    op.create_index('ix_ct_contract_type', 'contract_tasks', ['contract_id', 'task_type'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
        sa.Column('field_name', sa.String(length=200), nullable=False),
    sa.Column('field_category', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_value', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ef_contract_field', 'extracted_fields', ['contract_id', 'field_key'], unique=False)
    op.create_index('ix_ef_contract_review', 'extracted_fields', ['contract_id', 'review_status'], unique=False)
    op.create_index(op.f('ix_extracted_fields_contract_id'), 'extracted_fields', ['contract_id'], unique=False)
    op.create_table('ocr_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=30), nullable=False, comment='text / title / table / figure / list'),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('page_width', sa.Integer(), nullable=True),
    sa.Column('page_height', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_blocks_contract_id'), 'ocr_blocks', ['contract_id'], unique=False)
    op.create_index('ix_ocr_contract_page', 'ocr_blocks', ['contract_id', 'page_no'], unique=False)
    op.create_table('review_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False, comment='field / clause / risk / contract'),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False, comment='approve / reject / modify'),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_records_contract_id'), 'review_records', ['contract_id'], unique=False)
    op.create_table('contract_risks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=True),
    sa.Column('clause_id', sa.Uuid(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['contract_clauses.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['extracted_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_risks_contract_id'), 'contract_risks', ['contract_id'], unique=False)
    op.create_index('ix_cr_contract_level', 'contract_risks', ['contract_id', 'risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cr_contract_level', table_name='contract_risks')
    op.drop_index(op.f('ix_contract_risks_contract_id'), table_name='contract_risks')
    op.drop_table('contract_risks')
    op.drop_index(op.f('ix_review_records_contract_id'), table_name='review_records')
    op.drop_table('review_records')
    op.drop_index('ix_ocr_contract_page', table_name='ocr_blocks')
    op.drop_index(op.f('ix_ocr_blocks_contract_id'), table_name='ocr_blocks')
    op.drop_table('ocr_blocks')
    op.drop_index(op.f('ix_extracted_fields_contract_id'), table_name='extracted_fields')
    op.drop_index('ix_ef_contract_review', table_name='extracted_fields')
    op.drop_index('ix_ef_contract_field', table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index('ix_ct_contract_type', table_name='contract_tasks')
    op.drop_index(op.f('ix_contract_tasks_contract_id'), table_name='contract_tasks')
    op.drop_table('contract_tasks')
    op.drop_index(op.f('ix_contract_files_contract_id'), table_name='contract_files')
    op.drop_index('ix_cfile_contract_version', table_name='contract_files')
    op.drop_table('contract_files')
    op.drop_index(op.f('ix_contract_clauses_contract_id'), table_name='contract_clauses')
    op.drop_index('ix_cc_contract_type', table_name='contract_clauses')
    op.drop_table('contract_clauses')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_content_hash'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
